# Neural Network Batch Processing

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
from torchvision.transforms import transforms

torch.set_printoptions(linewidth=120)


In [2]:
train_set = torchvision.datasets.FashionMNIST(root='./data', train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))

train_loader = torch.utils.data.DataLoader(train_set, batch_size=10)

In [3]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)

    def forward(self, t):
        t = t

        t = F.relu(self.conv1(t))                                                  
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
        t = F.relu(self.fc2(t))

        t = self.out(t)

        return t


In [4]:
torch.set_grad_enabled(False)


In [5]:
network = Network()

In [6]:
network

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [7]:
data_loader = torch.utils.data.DataLoader(
    train_set, batch_size=10)


In [8]:
batch = next(iter(data_loader))


In [9]:
images, labels = batch


In [10]:
images.shape


torch.Size([10, 1, 28, 28])

In [11]:
labels.shape


torch.Size([10])

In [12]:
preds = network(images)


In [13]:
preds

tensor([[-0.0842, -0.0261, -0.1193, -0.0508,  0.0672,  0.0412,  0.0599,  0.0375, -0.0979, -0.0571],
        [-0.0880, -0.0287, -0.1226, -0.0396,  0.0596,  0.0396,  0.0649,  0.0368, -0.1069, -0.0519],
        [-0.0915, -0.0251, -0.1181, -0.0417,  0.0698,  0.0379,  0.0608,  0.0390, -0.1007, -0.0552],
        [-0.0892, -0.0217, -0.1178, -0.0428,  0.0679,  0.0383,  0.0611,  0.0393, -0.1010, -0.0565],
        [-0.0900, -0.0204, -0.1217, -0.0477,  0.0632,  0.0423,  0.0609,  0.0393, -0.1031, -0.0585],
        [-0.0926, -0.0290, -0.1163, -0.0422,  0.0606,  0.0421,  0.0654,  0.0312, -0.1043, -0.0470],
        [-0.0840, -0.0286, -0.1213, -0.0416,  0.0677,  0.0350,  0.0593,  0.0418, -0.1029, -0.0552],
        [-0.0866, -0.0344, -0.1214, -0.0453,  0.0633,  0.0384,  0.0620,  0.0379, -0.1007, -0.0480],
        [-0.0878, -0.0245, -0.1184, -0.0484,  0.0707,  0.0424,  0.0582,  0.0397, -0.0973, -0.0603],
        [-0.0896, -0.0228, -0.1151, -0.0458,  0.0660,  0.0462,  0.0564,  0.0321, -0.1016, -0.0569]])

In [14]:
preds.argmax(dim=1)


tensor([4, 6, 4, 4, 4, 6, 4, 4, 4, 4])

In [15]:
labels


tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [16]:
preds.argmax(dim=1).eq(labels)


tensor([False, False, False, False, False, False, False, False, False, False])

In [17]:
preds.argmax(dim=1).eq(labels).sum()


tensor(0)

In [18]:
def get_num_correct(preds, labels):
    return preds.argmax(dim=1).eq(labels).sum().item()


In [19]:
get_num_correct(preds, labels)


0