In [1]:
# broadcasting and element wise

In [2]:
import numpy as np
import torch

In [3]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

In [10]:
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [11]:
t1[0][0]

tensor(1.)

In [12]:
t2[0][0]

tensor(9.)

In [13]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [14]:
t1.shape

torch.Size([2, 2])

In [18]:
t1.size()

torch.Size([2, 2])

In [19]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [20]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [21]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [22]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [23]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [24]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [25]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [26]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [31]:
t1 = torch.tensor([
    [1,1],
    [2,2]
], dtype=torch.float32)

In [32]:
t2 = torch.tensor([2,4], dtype=torch.float32)

## lower rank t2 will be transformed via broadcasting to match the shape of high rank tensor t1

In [33]:
t1 + t2

tensor([[3., 5.],
        [4., 6.]])

# comaprison operation

In [34]:
t = torch.tensor([
    [0, 5, 0],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)


In [35]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [36]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [37]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [40]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])