In [1]:
import torch

In [2]:
t1 = torch.tensor([1,1,1])

In [3]:
t1

tensor([1, 1, 1])

In [4]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [5]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [8]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [9]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3,])

In [20]:
torch.cat((t1,t2,t3), dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [22]:
torch.stack((t1,t2,t3), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])