# Creating Tensors -- best options

In [2]:
import torch
import numpy as np

In [3]:
data = np.array([1,2,3])

In [6]:
t1 = torch.Tensor(data)        # class constructor
t2 = torch.tensor(data)        # factory function
t3 = torch.as_tensor(data)     # factory function
t4 = torch.from_numpy(data)    # factory function


In [8]:
t1.dtype,t2.dtype,t3.dtype,t4.dtype

(torch.float32, torch.int32, torch.int32, torch.int32)

In [9]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
torch.tensor(np.array([1.,2.,3.,4.,]))

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [12]:
torch.tensor(np.array([1,2,3]), dtype=torch.float32)

tensor([1., 2., 3.])

In [13]:
data = np.array([1,2,3])

In [14]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [18]:
data[0] = 0
data[1] = 0
data[2] = 0


### torch.Tensor and torch.tensor ---> copy data

In [19]:
print(t1)     # both create a copy of the numpy array
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


### torch.as_tensor and torch.from_numpy ---> share data

In [20]:
print(t3)
print(t4)           # both shared a copy of a numpy array

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
