In [1]:
import torch
import numpy as np

In [2]:
t = torch.Tensor()

# Tensor attributes

In [3]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [4]:
type(t)

torch.Tensor

In [5]:
device = torch.device('cuda:0')

In [6]:
device

device(type='cuda', index=0)

# Creating Data

In [7]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [8]:
torch.Tensor(data)       # float

tensor([1., 2., 3.])

In [9]:
torch.tensor(data)     # int

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
torch.as_tensor(data)  # int

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
torch.from_numpy(data)       # int

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.,])

In [13]:
t1.dtype

torch.int64

In [14]:
t2.dtype

torch.float32

In [15]:
t1 + t2

tensor([2., 4., 6.])

In [16]:
t3 = t1.cuda()

In [17]:
t3.device

device(type='cuda', index=0)

In [18]:
t1.device

device(type='cpu')

In [19]:
t1 + t3      # Tensor computations between 2 tensors depends on the device
             # t1 + t3 will output an error because t3 is runnung on the gpu while t1 is running on the cpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

# creating options without data

In [20]:
torch.eye(2)        # identity matrix

tensor([[1., 0.],
        [0., 1.]])

In [21]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [28]:
data2 = np.array([
    [1,2,3,4],
    [4,5,6,7]
])

In [30]:
data3 = torch.tensor(data2)

In [32]:
torch.(data3)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
torch.rand(2,2)

tensor([[0.3921, 0.9599],
        [0.0381, 0.7335]])