# Tensor reduction opts

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)


In [7]:
len(t.shape)           # rank 2

2

In [3]:
t.sum()

tensor(8.)

In [4]:
t.numel()               # number of elements within a tensor

9

In [5]:
t.sum().numel()

1

In [10]:
t.sum().numel() < t.numel()

True

# Common Tensor Reduction Operations

In [11]:
t.sum()

tensor(8.)

In [12]:
t.prod()

tensor(0.)

In [13]:
t.mean()

tensor(0.8889)

In [14]:
t.std()

tensor(1.1667)

# Reducing Tensors By Axes

In [15]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
], dtype=torch.float32)              # 3 x 4 rank-2 tensor


In [19]:
t.shape

torch.Size([3, 4])

In [20]:
t.sum(dim=0)                 # all 1 + 2 + 3 = 6 --> sum of all nums on each columns

tensor([6., 6., 6., 6.])

In [21]:
t.sum(dim=1)                  # 1+1+1+1, 2+2+2+2 +  sum of all nums on each row

tensor([ 4.,  8., 12.])

# Argmax Tensor Reduction Operation

In [22]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)


In [23]:
t.max()

tensor(5.)

In [25]:
t.argmax()         # argmax sits on the index of the flatten tensor 

tensor(11)

In [26]:
t.flatten()           # argmax of t_flat[11]

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [30]:
t_flat = t.flatten()
t_flat[11]

tensor(5.)

In [34]:
t

tensor([[1., 0., 0., 2.],
        [0., 3., 3., 0.],
        [4., 0., 0., 5.]])

In [32]:
t.max(dim=0)            #values = tensor([4., 3., 3., 5.]),
                        #indices = tensor([2, 1, 1, 2]))


torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [33]:
t.argmax(dim=0)       # returns only index values

tensor([2, 1, 1, 2])

In [35]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [36]:
t.argmax(dim=1)

tensor([3, 1, 3])

# Accessing Elements Inside Tensors

In [37]:
t = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float32)


In [38]:
t.mean()

tensor(5.)

In [39]:
t.mean().item()

5.0

In [42]:
t.mean(dim=0).tolist()           # mean row

[4.0, 5.0, 6.0]

In [43]:
t.mean(dim=1).tolist()           #mean column

[2.0, 5.0, 8.0]