In [32]:
import torch

In [33]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
    ], dtype=torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [34]:
t.reshape(1,12).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [35]:
t.size()

torch.Size([3, 4])

In [36]:
t.shape

torch.Size([3, 4])

In [37]:
len(t.shape)       # rank 2 -- length of the shape is the rank

2

In [38]:
torch.tensor(t.shape).prod()

tensor(12)

In [39]:
t.numel()     # number of elements

12

In [40]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [41]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [42]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [43]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [44]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [45]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [46]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [47]:
print(t.reshape(1,12))
print(t.reshape(1,12).size())

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [48]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().size())

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [49]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).size())

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [50]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [51]:
flatten(t)     # reshape and squeeze (flatten)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [52]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [53]:
t.reshape(1,12).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

# combining 2 tensors using cat() function

In [54]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

In [55]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [61]:
tcat_row = torch.cat([t1,t2], dim=0)      # row wise concat
tcat_row

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [62]:
tcat_row.shape

torch.Size([4, 2])

In [63]:
tcat_column = torch.cat([t1,t2], dim=1)    # column wise concatination
tcat_column

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [67]:
tcat_column.shape

torch.Size([2, 4])

In [68]:
len(tcat_column.shape)       #rank 2

2