In [1]:

dd = [[1,2,3],
      [4,5,6],
      [7,8,9]
      ]

In [6]:
import torch

t =  torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
len(t.shape)       # Rank = length of the shape of a nd-array
t.shape

torch.Size([3, 3])

In [7]:
type(t)

torch.Tensor

In [10]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [13]:
t = torch.tensor([
    [
        [2, 3, 4, 4], [2, 3, 4, 5]
    ]
])


In [14]:
t.shape

torch.Size([1, 2, 4])

In [15]:
dd = [
    [1, 2, 3, 4],
    [4, 5, 6, 7],
    [7, 8, 9, 10]
]


In [16]:
s = torch.tensor(dd)
s

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [17]:
s.shape

torch.Size([3, 4])