In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
from torchvision.transforms import transforms

torch.set_printoptions(linewidth=120)

In [3]:
train_set = torchvision.datasets.FashionMNIST(root='/.data', train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))

train_loader = torch.utils.data.DataLoader(train_set, batch_size=10)

In [4]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)

        self.out = nn.Linear(in_features=60, out_features=10)

    def forward(self, t):
        t = t

        t = F.relu(self.conv1(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t, kernel_size=2, stride=2)

        t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
        t = F.relu(self.fc2(t))

        t = self.out(t)

        return t

In [5]:
torch.set_grad_enabled(False)

In [6]:
network = Network()
network

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [7]:
sample = next(iter(train_set))

In [20]:
image, label = sample

In [21]:
image.shape

torch.Size([1, 28, 28])

In [22]:
output = image.unsqueeze(0)

In [8]:
batch = next(iter(train_loader))

In [9]:
images, labels = batch

In [10]:
images.shape

torch.Size([10, 1, 28, 28])

In [11]:
labels.shape

torch.Size([10])

In [12]:
pred = network(images)

In [13]:
pred

tensor([[ 0.0762, -0.1435, -0.0039, -0.0217, -0.0757,  0.0192,  0.0260, -0.0808, -0.0630, -0.0976],
        [ 0.0818, -0.1502,  0.0111, -0.0296, -0.0795,  0.0147,  0.0364, -0.0907, -0.0758, -0.1046],
        [ 0.0854, -0.1477,  0.0122, -0.0289, -0.0770,  0.0212,  0.0309, -0.0865, -0.0666, -0.1063],
        [ 0.0859, -0.1460,  0.0133, -0.0239, -0.0760,  0.0139,  0.0399, -0.0870, -0.0687, -0.1118],
        [ 0.0824, -0.1423,  0.0035, -0.0225, -0.0793,  0.0101,  0.0420, -0.0820, -0.0629, -0.1129],
        [ 0.0824, -0.1495,  0.0079, -0.0236, -0.0755,  0.0125,  0.0375, -0.0853, -0.0728, -0.1065],
        [ 0.0809, -0.1444,  0.0061, -0.0276, -0.0794,  0.0260,  0.0221, -0.0826, -0.0647, -0.1006],
        [ 0.0848, -0.1485,  0.0017, -0.0219, -0.0747,  0.0104,  0.0376, -0.0838, -0.0690, -0.1068],
        [ 0.0878, -0.1442,  0.0120, -0.0189, -0.0813,  0.0203,  0.0290, -0.0830, -0.0622, -0.0970],
        [ 0.0867, -0.1447,  0.0038, -0.0170, -0.0770,  0.0176,  0.0301, -0.0829, -0.0643, -0.0984]])

In [14]:
pred.argmax(dim=0)

tensor([8, 4, 3, 9, 7, 6, 4, 0, 8, 8])

In [15]:
labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [16]:
pred.argmax(dim=0).eq(labels)

tensor([False, False, False, False, False, False, False, False, False, False])

In [17]:
pred.argmax(dim=0).eq(labels).sum()

tensor(0)

In [18]:
def sum_correct_pred(pred, labels):
    return pred.argmax(dim=0).eq(labels).sum().item()

In [19]:
sum_correct_pred(pred, labels)

0